/**
 * Retrieval constants in one place (§A.5; research: retrieval-and-pipeline §1).
 * Tuning happens here, backed by eval evidence — never inline at call sites.
 */

/** Reciprocal rank fusion constant: score contribution = 1 / (RRF_K + rank). */
export const RRF_K = 60;

/** Each signal over-fetches this multiple of the requested topK before fusion. */
export const SIGNAL_FETCH_FACTOR = 4;

/** Results returned when the caller does not say how many it wants. */
export const DEFAULT_TOP_K = 8;

/** Entity-profile mode (F1/F4): gather up to this many of an entity's memories, no top-k. */
export const PROFILE_CEILING = 50;

/** Bounded budget for the conversational rewriter call (F3); fall back to raw query. */
export const REWRITE_TIMEOUT_MS = 4000;

/**
 * Capitalized tokens that are sentence mechanics, not names — the filter for
 * the fast-path query-entity heuristic (no model call, v1). English + Croatian,
 * matching the served languages of the golden set (§B.4).
 */
export const QUERY_ENTITY_STOPWORDS = new Set(
  [
    // English question/function words that start sentences.
    'what',
    'who',
    'whom',
    'whose',
    'when',
    'where',
    'why',
    'how',
    'which',
    'do',
    'does',
    'did',
    'is',
    'are',
    'was',
    'were',
    'am',
    'be',
    'been',
    'can',
    'could',
    'should',
    'would',
    'will',
    'shall',
    'may',
    'might',
    'must',
    'have',
    'has',
    'had',
    'the',
    'a',
    'an',
    'i',
    'my',
    'we',
    'our',
    'you',
    'your',
    'they',
    'their',
    'he',
    'she',
    'it',
    'its',
    'this',
    'that',
    'these',
    'those',
    'and',
    'or',
    'but',
    'if',
    'then',
    'so',
    'not',
    'no',
    'yes',
    'please',
    'tell',
    'show',
    'list',
    'remind',
    'give',
    'me',
    'about',
    'of',
    'for',
    'to',
    'in',
    'on',
    'at',
    'by',
    'with',
    'from',
    'before',
    'after',
    // Croatian counterparts.
    'što',
    'sto',
    'tko',
    'koga',
    'komu',
    'kome',
    'kada',
    'kad',
    'gdje',
    'kamo',
    'kuda',
    'zašto',
    'zasto',
    'kako',
    'koliko',
    'koji',
    'koja',
    'koje',
    'koju',
    'čiji',
    'ciji',
    'je',
    'li',
    'sam',
    'si',
    'smo',
    'ste',
    'su',
    'sad',
    'bi',
    'bih',
    'bismo',
    'hoće',
    'hoce',
    'hoću',
    'hocu',
    'mogu',
    'može',
    'moze',
    'moram',
    'trebam',
    'treba',
    'imam',
    'ima',
    'da',
    'ne',
    'i',
    'ili',
    'ali',
    'pa',
    'te',
    'za',
    'na',
    'u',
    'o',
    'od',
    'do',
    's',
    'sa',
    'iz',
    'kod',
    'prije',
    'poslije',
    'nakon',
    'reci',
    'pokaži',
    'pokazi',
    'podsjeti',
  ].map((word) => word.toLowerCase()),
);
