import { createHash } from 'node:crypto';
import { z } from 'zod';
import { PASSPORT_VERSION } from '@cogeto/shared';

/**
 * The Memory Passport format contract (§B.5, decision record 0029) — the
 * IN-CODE authority for the artifact's shape, mirrored by the published JSON
 * Schema in `docs/passport-schema/` (both stamped with `passport_version`; kept
 * in lockstep). The executor builds documents that satisfy these schemas and
 * the `passport_schema_valid` test re-validates the generated bytes against
 * them, so a drift between the artifact and its documented format fails the
 * build.
 *
 * Nothing here reaches for a table or a gate — assembly consumes already-gated
 * rows the executor fetched through the Principal-scoped interfaces. This module
 * is pure format + hashing.
 */

/** Canonical document paths inside the archive. */
export const PASSPORT_PATHS = {
  manifest: 'manifest.json',
  manifestSig: 'manifest.json.sig',
  memories: 'memories.json',
  tasks: 'tasks.json',
  receipts: 'receipts.json',
  readme: 'README.txt',
  attachmentsDir: 'attachments',
} as const;

/** Hex SHA-256 of a document's exact bytes — what the manifest records. */
export function sha256Hex(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

const iso = z.string().datetime({ offset: true });
const isoOrPlain = z.string(); // receipts carry pre-existing ISO strings verbatim

// ── memories.json ────────────────────────────────────────────────────────────
export const provenanceSchema = z.object({
  source_type: z.string(),
  source_id: z.string(),
  /** A short excerpt of the originating source (owner's own memories only), or null. */
  context: z.string().nullable(),
  /** File provenance for `source_type: file`, else null. */
  file: z
    .object({
      filename: z.string().nullable(),
      content_type: z.string().nullable(),
      size_bytes: z.number().nullable(),
    })
    .nullable(),
  /** Archive path of the included original bytes, when include_originals; else null. */
  attachment_path: z.string().nullable(),
});

export const memoryExportSchema = z.object({
  id: z.string(),
  content: z.string().nullable(),
  status: z.string(),
  scope: z.enum(['private', 'shared']),
  sensitive: z.boolean(),
  owner_id: z.string(),
  /** false when this is a shared fact owned by a teammate (still exported, marked). */
  owned_by_me: z.boolean(),
  entities: z.array(z.string()),
  subject_entity: z.string().nullable(),
  kind: z.string().nullable(),
  valid_from: z.string().nullable(),
  valid_until: z.string().nullable(),
  created_at: z.string(),
  updated_at: z.string().nullable(),
  /** Successor pointer — the supersession chain is reconstructed from these. */
  superseded_by: z.string().nullable(),
  temporal_unresolved: z.array(z.string()),
  provenance: provenanceSchema,
});
export type MemoryExport = z.infer<typeof memoryExportSchema>;

export const memoriesDocSchema = z.object({
  passport_version: z.literal(PASSPORT_VERSION),
  count: z.number().int().nonnegative(),
  memories: z.array(memoryExportSchema),
});

// ── tasks.json ───────────────────────────────────────────────────────────────
export const taskExportSchema = z.object({
  id: z.string(),
  title: z.string(),
  status: z.string(),
  condition_text: z.string().nullable(),
  due: z.string().nullable(),
  dormant: z.boolean(),
  from_uncertain: z.boolean(),
  derived_from_memory_id: z.string(),
  scope: z.enum(['private', 'shared']),
  created_at: z.string(),
  updated_at: z.string().nullable(),
});
export type TaskExport = z.infer<typeof taskExportSchema>;

export const tasksDocSchema = z.object({
  passport_version: z.literal(PASSPORT_VERSION),
  count: z.number().int().nonnegative(),
  tasks: z.array(taskExportSchema),
});

// ── receipts.json ────────────────────────────────────────────────────────────
/** Exactly the fields `verifyChain` needs — the receipt stays independently checkable. */
export const receiptExportSchema = z.object({
  id: z.string(),
  source_type: z.string(),
  source_id: z.string(),
  counts_json: z.unknown(),
  signed_at: isoOrPlain,
  confirmed_at: isoOrPlain,
  prev_hash: z.string(),
  hash: z.string(),
  signature: z.string(),
});
export type ReceiptExport = z.infer<typeof receiptExportSchema>;

export const receiptsDocSchema = z.object({
  passport_version: z.literal(PASSPORT_VERSION),
  count: z.number().int().nonnegative(),
  /** The instance public key — receipts verify against it without contacting Cogeto. */
  instance_public_key_pem: z.string(),
  receipts: z.array(receiptExportSchema),
});

// ── manifest.json ────────────────────────────────────────────────────────────
export const manifestDocumentSchema = z.object({
  path: z.string(),
  sha256: z.string().regex(/^[0-9a-f]{64}$/),
  bytes: z.number().int().nonnegative(),
});

export const manifestSchema = z.object({
  passport_version: z.literal(PASSPORT_VERSION),
  generated_at: iso,
  subject: z.object({ user_id: z.string(), display_name: z.string().nullable() }),
  instance: z.object({
    public_key_pem: z.string(),
    signature_algorithm: z.literal('ed25519'),
    /** The archive path of the detached signature over THIS manifest's bytes. */
    signature_file: z.literal(PASSPORT_PATHS.manifestSig),
  }),
  options: z.object({ include_originals: z.boolean() }),
  counts: z.object({
    memories: z.number().int().nonnegative(),
    tasks: z.number().int().nonnegative(),
    receipts: z.number().int().nonnegative(),
    attachments: z.number().int().nonnegative(),
  }),
  documents: z.array(manifestDocumentSchema),
});
export type Manifest = z.infer<typeof manifestSchema>;

/** Stable, human-readable JSON bytes for a document (2-space indent, LF). */
export function documentBytes(value: unknown): Buffer {
  return Buffer.from(`${JSON.stringify(value, null, 2)}\n`, 'utf8');
}
