import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { writeFile } from 'node:fs/promises';
import { Pool } from 'pg';
import { run } from 'graphile-worker';
import type { Runner } from 'graphile-worker';
import { loadConfig } from './config';
import { createLogger, PinoNestLogger } from './logger';
import { createWorkerRootModule } from './worker-root.module';
import { createDb, describeErrorLine, ensureInstanceKeys } from '../infrastructure/index';
import { logRedactionState } from './redaction-boot';
import {
  ACTIVE_PROMPTS,
  DREAM_CRONTAB,
  DreamingService,
  IngestionPipeline,
} from '../ingestion/index';
import {
  DeletionExecutor,
  IntegritySweep,
  MemoryObjectStore,
  MemoryStore,
  SWEEP_CRONTAB,
} from '../memory/index';
import { APPROVAL_EXPIRY_CRONTAB, ApprovalExecutor, ApprovalService } from '../agents/index';
import { TASK_PROMPTS, TASKS_REMINDERS_CRONTAB, TasksEngine } from '../tasks/index';
import { ANSWER_PROMPT, QUERY_REWRITE_PROMPT } from '../retrieval/index';
import { loadPrompt, ModelGateway, recordPromptVersion } from '../model-gateway/index';
import { buildTaskList } from './worker-tasks';
import {
  credentialsBanner,
  DEMO_RESET_JOB_TYPE,
  DemoResetInProgressError,
  ensureDemoCredentials,
  establishDemoSession,
  resetDemoWorld,
} from './demo/index';

const HEARTBEAT_FILE = '/tmp/worker-heartbeat';
const HEARTBEAT_INTERVAL_MS = 10_000;

/**
 * worker — the slow-path process (§A.1): Graphile Worker runner over the
 * Postgres queue (§A.3) plus the Nest application context for module services.
 * No HTTP. Assumes migrations already ran (init container, §A.2).
 */
async function main(): Promise<void> {
  const config = loadConfig();
  const logger = createLogger(config.logLevel);
  logRedactionState(logger, config); // QS-21: state the effective posture loudly.

  const context = await NestFactory.createApplicationContext(
    createWorkerRootModule(config) as never,
    { logger: new PinoNestLogger(logger) },
  );
  context.enableShutdownHooks();

  // QS-38: explicit pool ceiling. This pool backs BOTH the graphile runner and
  // the job handlers' idempotency transactions (which the pipeline holds open
  // across model calls), so it must clear worker concurrency (2) with headroom
  // for the single-flight locks and graphile's own connections.
  const pool = new Pool({ connectionString: config.databaseUrl, max: config.pgPoolMax });
  const db = createDb(pool);

  // Register the active prompt versions (§B.7) — also the immutability check:
  // a released version whose file hash changed fails the boot.
  for (const ref of [...ACTIVE_PROMPTS, ...TASK_PROMPTS, ANSWER_PROMPT, QUERY_REWRITE_PROMPT]) {
    const prompt = await loadPrompt(ref.family, ref.version);
    await recordPromptVersion(db, prompt);
    logger.info(
      { family: prompt.family, version: prompt.version, sha256: prompt.contentHash.slice(0, 12) },
      'prompt version registered',
    );
  }

  // Idempotent Qdrant collection + payload-index creation (§A.4).
  await context.get(MemoryStore).ensureIndexReady();
  logger.info('memory vector collection ready');

  // Receipt signing needs the instance keypair (§B.1). Compose: generated by
  // the migrate init job, mounted read-only here — this is then a no-op check.
  // Bare local runs (no init job) generate into the gitignored default dir.
  try {
    await ensureInstanceKeys(config.instanceKeyDir);
  } catch (error) {
    logger.warn(
      { err: error, dir: config.instanceKeyDir },
      'could not ensure instance keys (read-only mount without keys?) — signing will fail until the migrate job runs',
    );
  }

  const pipeline = context.get(IngestionPipeline);
  const objects = context.get(MemoryObjectStore);
  const gateway = context.get(ModelGateway);
  const taskList = buildTaskList(db, {
    pipeline,
    memoryStore: context.get(MemoryStore),
    deletionExecutor: context.get(DeletionExecutor),
    integritySweep: context.get(IntegritySweep),
    dreaming: context.get(DreamingService),
    tasksEngine: context.get(TasksEngine),
    approvalService: context.get(ApprovalService),
    approvalExecutor: context.get(ApprovalExecutor),
    objects,
    gateway,
    log: (event, message) => logger.info(event, message),
  });

  // Ana sandbox (decision 0022 ruling 2): the scheduled reset is registered +
  // scheduled ONLY on a demo instance — never on a customer instance. It reuses
  // the demo Principal from the seed job and runs the same wipe-and-reseed
  // routine. One more crontab LINE (demoLine), never a second scheduler.
  let demoLine = '';
  if (config.demoMode) {
    taskList[DEMO_RESET_JOB_TYPE] = async () => {
      const { api, ownerId } = await establishDemoSession(config);
      try {
        await resetDemoWorld({
          pool,
          db,
          api,
          ownerId,
          objects,
          gateway,
          qdrantUrl: config.qdrantUrl,
          qdrantApiKey: config.qdrantApiKey,
          embeddingModel: config.mistralEmbedModel,
          strict: false, // a failed scheduled reset logs; the next one repairs it
          excludeTask: DEMO_RESET_JOB_TYPE, // don't count our own running job
          log: (message) => logger.info({}, message),
        });
        // A reset rotates the sandbox login password (decision 0027); surface it.
        const creds = await ensureDemoCredentials(config.demoSessionFile, { rotate: true });
        logger.info({}, credentialsBanner(creds));
        logger.info({}, 'scheduled demo reset completed');
      } catch (error) {
        // QS-33: another reset already holds the lock — skip cleanly, don't fail
        // the job (which would retry into the running reset).
        if (error instanceof DemoResetInProgressError) {
          logger.info({}, 'scheduled demo reset skipped — another reset in progress');
          return;
        }
        throw error;
      }
    };
    demoLine = `\n${config.demoResetCron} ${DEMO_RESET_JOB_TYPE}`;
    logger.info({ cron: config.demoResetCron }, 'demo mode: scheduled reset enabled');
  }

  const runner: Runner = await run({
    pgPool: pool,
    concurrency: 2,
    taskList,
    // Nightly schedule (graphile cron): the 03:00 integrity sweep (§A.7 step 4),
    // the 03:30 dreaming cycle (§B.6; decision 0011), then the 03:40 task
    // reminders pass (F3 handoff §2 — one more crontab LINE, never a second
    // scheduler), plus the every-5-minute approval expiry pass (§A.8; O1-B), plus
    // the demo reset on a demo instance. On-demand sweep/dream go through their
    // entrypoints instead.
    //
    // QS-39: graphile cron honours the process timezone, so the worker container
    // pins TZ=UTC (compose) — these times are UTC and DST never shifts them. A
    // DST transition can still make a wall-clock hour repeat/skip on non-UTC
    // hosts; the single-flight advisory lock on each recurring job (worker-tasks)
    // makes a double-fire a clean skip, and the jobs are idempotent by design.
    crontab: `${SWEEP_CRONTAB}\n${DREAM_CRONTAB}\n${TASKS_REMINDERS_CRONTAB}\n${APPROVAL_EXPIRY_CRONTAB}${demoLine}`,
    noHandleSignals: true,
  });
  logger.info('cogeto worker started (graphile runner + task registry)');

  const heartbeat = setInterval(() => {
    void writeFile(HEARTBEAT_FILE, new Date().toISOString()).catch((error: unknown) => {
      logger.warn({ err: error }, 'heartbeat write failed');
    });
  }, HEARTBEAT_INTERVAL_MS);
  await writeFile(HEARTBEAT_FILE, new Date().toISOString());

  let stopping = false;
  const shutdown = async (): Promise<void> => {
    if (stopping) return;
    stopping = true;
    clearInterval(heartbeat);
    await runner.stop();
    await pool.end();
    await context.close();
    process.exit(0);
  };
  process.on('SIGTERM', () => void shutdown());
  process.on('SIGINT', () => void shutdown());
}

// Top-level handlers log the error class + a scrubbed, bounded message only —
// never the raw error (stack / `received …` can carry secrets or model output),
// QS-22.
process.on('unhandledRejection', (reason: unknown) => {
  console.error(`unhandledRejection: ${describeErrorLine(reason)}`);
});
process.on('uncaughtException', (error: unknown) => {
  console.error(`uncaughtException: ${describeErrorLine(error)}`);
  process.exit(1);
});

main().catch((error: unknown) => {
  console.error(`worker failed to start: ${describeErrorLine(error)}`);
  process.exit(1);
});
